name: Python Tests
on: [ push, pull_request ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    name: Python tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest ./tests --alluredir=../allure-results --disble-warnings
        continue-on-error: true

      - name: Archive alllure results
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: allure-results
          retention-days: 1

  generate-report:
    runs-on: ubuntu-latest
    needs: test
    name: Generate Allure Report
    steps:
      - uses: actions/setup-java@v3
        with:
          distribution: 'microsoft'
          java-version: '17'
      - name: Install Allure
        run: |
          sudo wget https://github.com/allure-framework/allure2/releases/download/2.32.0/allure-2.32.0.tgz
          sudo tar -xzvf allure-2.32.0.tgz -C /opt/
          sudo ln -s /opt/allure-2.32.0/bin/allure /usr/bin/allure
      - name: Download allure results
        uses: actions/download-artifact@v3
        with:
          name: allure-results
          path: allure-results
      - name: Generate Allure report
        run: allure generate -c allure-results -o _site
      - name: Upload Allure report
        uses: actions/upload-artifact@v3
        with:
          name: github-pages
          path: _site
          retention-days: 1

    publish-report:
      runs-on: ubuntu-latest
      needs: generate-report
      name: Publish Allure Report to GitHub Pages
      steps:
        - name: Download Allure report artifact
          uses: actions/download-artifact@v3
          with:
            name: github-pages
            path: _site
        - name: Deploy to GitHub Pages
          uses: actions/deploy-pages@v1.2.9




